title: "Legal or Nah?"
description: "A fun Q&A site answering weird 'Is it legal…?' questions"
baseurl: ""  # Deployed at root domain
url: "https://legalornah.com"

# 🚫 Removed the default Minima theme to stop unwanted CSS builds
# theme: minima   <-- Removed this line

# ✅ Correct CSS path specified globally & sitemap config combined
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
      css: /assets/css/main.css
      sitemap: true  # Ensures pages are included in sitemap

  - scope:
      path: "drafts"
    values:
      sitemap: false  # Excludes drafts from sitemap

# 🧹 ✅ EXCLUDE SECTION (Top Level)
exclude:
  - batchdeploy_cheatsheet.html
  - cheatsheet.html
  - welcome-to-jekyll/         # ✅ Correct source folder exclusion
  - welcome-to-jekyll.md       # ✅ If it's a markdown file causing it
  - _site/welcome-to-jekyll/
  - base_question.txt
  - "*.py"
  - "*.docx"
  - requirements.txt
  - feed.xml
  - feed.json
  - drafts/
  - node_modules/
  - package.json
  - Gemfile
  - Gemfile.lock
  - vendor/

# Permalink and Markdown Settings
markdown: kramdown
permalink: /:title/

# ✅ Combined Plugins Section
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-json-feed

# ✅ Combined Collections Section
collections:
  questions:
    output: true
    permalink: /questions/:title/
  search:
    output: true

include:
  - search.json.liquid
