title: "Legal or Nah?"
description: "A fun Q&A site answering weird 'Is it legal…?' questions"
baseurl: ""  # Deployed at root domain
url: "https://legalornah.com"

# 🚫 Removed the default Minima theme to stop unwanted CSS builds
# theme: minima   <-- Removed this line

# ✅ Correct CSS path specified globally
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
      css: /assets/css/main.css

# Permalink and Markdown Settings
markdown: kramdown
permalink: /:title/

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  questions:
    output: true
    permalink: /questions/:title/
