power-bank:
  title: "INIU Portable Charger, 20000mAh Power Bank"
  asin: "B07YPY31FL"
  image: "/assets/images/power_bank.jpg"
  description: "Stay powered up on the go with this high-capacity portable charger—perfect for travelers, campers, and anyone who needs reliable power anytime, anywhere."
  region: "au"
