funny-legal-books:
  title: "Lawyers Have Feelings Too"
  asin: "1986942597"
  image: "https://m.media-amazon.com/images/I/319NMV9HxdL._SY385_.jpg"
  description: "A hilarious take on the legal profession—perfect for anyone who loves law with a side of humor."
  region: "au"